<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "usertools"
 *
 * Auto generated by Extension Builder 2020-03-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'User tools',
    'description' => 'Collection of user tools: 
- list all users
- edit the profile (image, phone number, email address, visualisation properties etc.) 
# 2.1.1 :: optimize the fast search input field layout
# 2.1.2 :: optimize the fast serach algorithm
',
    'category' => 'plugin',
    'author' => 'Clemens Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.2',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-11.5.99',
            'news' => '8.6.0-9.4.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
