services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cylancer\Usertools\:
    resource: '../Classes/*'
  
  Cylancer\Usertools\Upgrades\UsertoolsUpgradeCTypeWizard:
    tags:
      - name: install.upgradewizard
  Cylancer\Usertools\Upgrades\UsertoolsUpgradeWizard:
    tags:
      - name: install.upgradewizard      